In [1]:
import numpy as np


In [2]:
#create a 1d arr of range 0 to n
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# 3*3 numpy arry of all ones
np.ones((3,3), dtype = int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [4]:
#4*4 numpy arry of all zeros
np.zeros((4,4),dtype = int)


array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [5]:
#3*3 numpy arry of all true 
np.ones((3,3), dtype = bool)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [5]:
#Extrat all odd number from arry 
#input array(0,1...9)
#output arraay(1,3,5,7,9)
arr[arr % 2 == 1]

array([1, 3, 5, 7, 9])

In [6]:
#Extrat all even number from arry
arr[arr % 2  == 0]

array([0, 2, 4, 6, 8])

In [7]:
#change all odd number with all -1
out = np.where(arr % 2 == 1, -1,arr)
out

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

In [8]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
#reshape the array from 1d arry to 2d arry
arr = np.arange(10)
arr.reshape(2,-1)# -1 decide number of columns


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [10]:
arr1 = np.arange(12)
arr1.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
arr2 = np.arange(9)
arr2.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [12]:
#stack a to b
a = np.arange(10).reshape(2,5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [13]:
b = np.repeat(1,10).reshape(2,5)
b

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [14]:
#method one 
np.concatenate([a,b],axis = 0)  #by default axis = 0 

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [15]:
np.concatenate([a,b],axis = 1)


array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [16]:
#method 2
np.vstack([a,b])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [17]:
#method 3
np.r_[a,b]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [18]:
np.hstack([a,b])

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [19]:
np.c_[a,b]

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

In [20]:
#input a = np.array([1,2,3])
#output array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])
a = np.array([1,2,3])

In [21]:
a

array([1, 2, 3])

In [22]:
np.repeat(a,3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [23]:
np.r_[np.repeat(a, 3), np.tile(a, 3)]

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 1, 2, 3, 1, 2, 3, 1, 2, 3])

In [24]:
# common element of a and b
#input a = np.array([1,2,3,2,3,4,3,4,5,6])
#b = np.array([7,2,10,2,7,4,9,4,9,8])

#output array([2,4])
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [25]:
np.intersect1d(a,b)

array([2, 4])

In [26]:
#From array a remove all items present in array b

#input a = np.array([1,2,3,4,5])
    #  b = np.array([5,6,7,8,9])

#output array([1,2,3,4])

a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

In [27]:
np.setdiff1d(a,b)

array([1, 2, 3, 4])

In [28]:
c = np.array([3,4,5])

In [29]:
np.setdiff1d(a,c)

array([1, 2])

In [30]:
# Get the positions where elements of a and b match
# input a = np.array([1,2,3,2,3,4,3,4,5,6])
#       b = np.array([7,2,10,2,7,4,9,4,9,8])

#output (array([1, 3, 5, 7]),)

a =  np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

In [31]:
np.where(a == b)

(array([1, 3, 5, 7], dtype=int64),)

In [33]:
# print that position a divide the element of b

np.where(a%b == 0)

(array([1, 3, 5, 7], dtype=int64),)

In [32]:
#getting all position number  from array a arr[pos] is even
np.where(a%2 == 0)

(array([1, 3, 5, 7, 9], dtype=int64),)

In [33]:
#getting all even position number from array a where arr[pos] is odd
np.where(a%2 != 0)

(array([0, 2, 4, 6, 8], dtype=int64),)

In [34]:
#getting all odd position number from array b where arr[pos] is even
np.where(b%2 == 0)

(array([1, 2, 3, 5, 7, 9], dtype=int64),)

In [35]:
#getting all odd position number from array b where arr[pos] is odd
np.where(b%2 != 0)

(array([0, 4, 6, 8], dtype=int64),)

In [36]:
#Get all items between 5 and 10 from a.
#input a = np.array([2, 6, 1, 9, 10, 3, 27])
#output (array([6, 9, 10]),)

a = np.array([2, 6, 1, 9, 10, 3, 27])

In [37]:
#method 1
index = np.where((a >= 5) & (a <= 10))
a[index]

array([ 6,  9, 10])

In [38]:
#method 2
index = np.where(np.logical_and(a>=5, a<=10))
a[index]

array([ 6,  9, 10])

In [39]:
#method 3
a[(a>=5) & (a<=10)]

array([ 6,  9, 10])

In [40]:
#How to extract all numbers between a given range from a numpy array?

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)

5

In [41]:
#Convert the function maxx that works on two scalars, to work on two arrays.

#input a = np.array([5, 7, 9, 8, 6, 4, 5])
#      b = np.array([6, 3, 4, 8, 9, 7, 1])

#output  array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])

In [43]:
print_max = np.vectorize(maxx , otypes = [int])
print_max(a,b)

array([6, 7, 9, 8, 9, 7, 5])

In [94]:
#getting prime number from both the array a and b 

def is_prime(num):
    if num == 0 or num == 1:
        return 
    for i in range(2,num):
        if num % i == 0:
            return
    return(num)

In [73]:
is_prime(2)


2

In [74]:
is_prime(3)

3

In [75]:
is_prime(4)


In [96]:
print_prime = np.vectorize(is_prime, otypes = [float])
print_prime(a)


array([ 5.,  7., nan, nan, nan, nan,  5.])

In [46]:
# Swap columns 1 and 2 in the array arr.
#input arr = np.arange(9).reshape(3,3)
#output
#  array([[1, 0, 2],
#>        [4, 3, 5],
#>        [7, 6, 8]])

arr = np.arange(9).reshape(3,3)
arr


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [47]:
arr[:,[1,0,2]]

array([[1, 0, 2],
       [4, 3, 5],
       [7, 6, 8]])

In [48]:
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [49]:
arr[:,[2,1,0]]


array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [50]:
arr[[2,1,0],[2,1,0]]

array([8, 4, 0])

In [51]:
arr[[2,1,0],:]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [52]:
arr[[2],:]

array([[6, 7, 8]])

In [53]:
arr[:,[2]]

array([[2],
       [5],
       [8]])

In [56]:
# Reverse the rows of a 2D array arr.
ar = np.arange(9).reshape(3,3)
ar

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [57]:
ar[::-1,:]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [58]:
# Reverse the columns of a 2D array arr.
arr[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [56]:
ar

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [57]:
ar[:,::-1]

array([[2, 1, 0],
       [5, 4, 3],
       [8, 7, 6]])

In [59]:
# Create a 2D array of shape 5x3 to contain random decimal numbers between 5 and 10.
# method 1

rand_arr = np.random.randint(low = 5, high = 10 , size = (5,3)) + np.random.random((5,3))
rand_arr

array([[8.49809486, 7.26476755, 5.45163251],
       [6.01246806, 7.81360295, 5.96435675],
       [7.73167163, 7.47871973, 6.29233469],
       [6.09223878, 5.48222281, 9.13935925],
       [9.00971336, 7.3823881 , 9.9666712 ]])

In [60]:
# method 2

rand_arr = np.random.uniform(5,10,size = (5,4))

In [61]:
rand_arr

array([[9.06769456, 9.16301921, 9.48626686, 5.87302946],
       [5.30127668, 9.37712892, 5.53863502, 8.94521935],
       [8.44042431, 8.46149021, 5.88852836, 6.75196551],
       [7.90490439, 7.45149253, 9.10607117, 7.75235523],
       [6.50039319, 5.12308505, 7.09727336, 6.83799422]])

In [62]:
arr = np.random.random((5,3))  #give random number from 0 to 1
arr

array([[0.10648193, 0.24390202, 0.78394426],
       [0.50961605, 0.27991941, 0.76456394],
       [0.87141948, 0.91875135, 0.69900175],
       [0.52980376, 0.28497411, 0.13542634],
       [0.96028056, 0.41898363, 0.25888355]])

In [63]:
arr = np.random.random([5,3])  # altenative way of passing argument
arr

array([[0.98093048, 0.42045487, 0.07800048],
       [0.71411886, 0.50554794, 0.58862454],
       [0.08019663, 0.4906778 , 0.96806248],
       [0.92933046, 0.51593117, 0.50249706],
       [0.56456412, 0.55673538, 0.46242469]])

In [64]:
# Print or show only 3 decimal places of the numpy array rand_arr.
np.set_printoptions(precision=4)

In [65]:
arr

array([[0.9809, 0.4205, 0.078 ],
       [0.7141, 0.5055, 0.5886],
       [0.0802, 0.4907, 0.9681],
       [0.9293, 0.5159, 0.5025],
       [0.5646, 0.5567, 0.4624]])

In [80]:
# Pretty print rand_arr by suppressing the scientific notation (like 1e10)
np.set_printoptions(suppress=False)
np.random.seed(100)  #create random array

In [81]:
arr = np.random.random([3,3])/1e3
arr

array([[5.434049e-04, 2.783694e-04, 4.245176e-04],
       [8.447761e-04, 4.718856e-06, 1.215691e-04],
       [6.707491e-04, 8.258528e-04, 1.367066e-04]])

In [74]:
np.set_printoptions(suppress=True, precision = 6)

In [75]:
arr

array([[0.000253, 0.000533, 0.000892],
       [0.000242, 0.000418, 0.000868],
       [0.000286, 0.000138, 0.000051]])

In [82]:
# Limit the number of items printed in python numpy array a to a maximum of 6 elements.

# Input  array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])
#output array([ 0,  1,  2, ..., 12, 13, 14])
np.set_printoptions(threshold = False)
a = np.arange(15)
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [83]:
np.set_printoptions(threshold = np.nan)  #limits the value to the 7 element only

In [84]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [85]:
b = np.arange(20)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [86]:
np.set_printoptions(threshold = 10)

In [87]:
b

array([ 0,  1,  2, ..., 17, 18, 19])

In [88]:
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [89]:
a

array([ 0,  1,  2, ..., 12, 13, 14])

In [90]:
# Import the iris dataset keeping the text intact.
# Solution
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')
names = ('sepallength', 'sepalwidth', 'petallength', 'petalwidth', 'species')

In [91]:
# Print the first 3 rows
iris[:3]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa']], dtype=object)

In [92]:
# Extract the text column species from the 1D iris imported in previous question.
# Input:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_1d = np.genfromtxt(url, delimiter=',', dtype=None)
print(iris_1d.shape)

# Solution:
species = np.array([row[4] for row in iris_1d])
species[:5]
#> (150,)
#> array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
#>        b'Iris-setosa'],
#>       dtype='|S18')

(150,)


C:\Users\Virender Pal Singh\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: VisibleDeprecationWarning: Reading unicode strings without specifying the encoding argument is deprecated. Set the encoding, use None for the system default.
  after removing the cwd from sys.path.


array([b'Iris-setosa', b'Iris-setosa', b'Iris-setosa', b'Iris-setosa',
       b'Iris-setosa'], dtype='|S18')

In [93]:
# find the mean standard deviasion median of the dataset

x = np.random.uniform(1,10,size=(3,3))

In [94]:
x

array([[6.17584 , 9.021898, 2.882819],
       [2.667954, 1.975392, 2.977277],
       [9.807614, 8.305148, 2.547469]])

In [95]:
# mean 
mean = np.mean(x)

In [96]:
mean

5.151267955025313

In [97]:
# standard deviation 
std = np.std(x)

In [98]:
std

2.991932520067635

In [99]:
# median 
median = np.median(x)

In [100]:
median

2.9772774336249297

In [101]:
# calculating the mean std and median for dataset from url
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

sepallength = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0])

sepallength

array([5.1, 4.9, 4.7, ..., 6.5, 6.2, 5.9])

In [102]:
# Solution
mu, med, sd = np.mean(sepallength), np.median(sepallength), np.std(sepallength)
print(mu, med, sd)

5.843333333333334 5.8 0.8253012917851409


In [103]:
# to normalize an array so the values range exactly between 0 and 1?

# for random dataset 

arr = np.random.uniform(1,10,size = (4,4))
arr

array([[8.346023, 3.466664, 4.885338, 9.460268],
       [8.358844, 4.025008, 2.578694, 4.355488],
       [1.051197, 3.271837, 8.160963, 1.137295],
       [6.38959 , 6.434241, 1.946329, 4.437491]])

In [104]:
Smin , Smax = arr.min(), arr.max()

In [105]:
print(Smin,Smax)

1.0511965661731608 9.460268376601372


In [106]:
# method 1 for normalize of vector or matrix
S = (arr - Smin) / (Smax - Smin)

In [107]:
print(S)

[[0.867495 0.287245 0.455953 1.      ]
 [0.86902  0.353643 0.181649 0.392944]
 [0.       0.264077 0.845488 0.010239]
 [0.634837 0.640147 0.106448 0.402695]]


In [108]:
# method 1' for normalize of vector or matrix
S = (arr - Smin) / arr.ptp()

In [109]:
print(S)

[[0.867495 0.287245 0.455953 1.      ]
 [0.86902  0.353643 0.181649 0.392944]
 [0.       0.264077 0.845488 0.010239]
 [0.634837 0.640147 0.106448 0.402695]]


In [110]:
# standard method for normalize of matrix or vectors
mean = np.mean(arr)
std = np.std(arr) # standard deviation

normalize = abs(x - mean)/std
normalize

array([[0.491293, 1.582173, 0.770907],
       [0.853263, 1.118719, 0.734701],
       [1.883335, 1.307447, 0.899445]])

In [111]:
# computing the softmax value given vector or matrix
arr = np.random.uniform(1,10,size=(1,15))
arr

array([[1.328285, 9.013704, 9.828288, ..., 7.922037, 3.256257, 3.573061]])

In [113]:
# compute the softmax
def softmax(x):
    
    e_x = np.exp(x - np.max(x))
    return e_x / e_x.sum(axis = 0)
#np.exp(1)

2.718281828459045

In [114]:
softmax(arr)

array([[1., 1., 1., ..., 1., 1., 1.]])

In [115]:
# calculating the percentile for given dataset 

# calculatin the 5th and 95th percentile

np.percentile(arr, q = [5,95])

array([1.284985, 9.258926])

In [116]:
# Input
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='object')


In [117]:
# Method 1
i, j = np.where(iris_2d)

In [118]:
i

array([  0,   0,   0, ..., 149, 149, 149], dtype=int64)

In [119]:
j

array([0, 1, 2, ..., 2, 3, 4], dtype=int64)

In [120]:
# i, j contain the row numbers and column numbers of 600 elements of iris_x
np.random.seed(100)
iris_2d[np.random.choice((i), 20), np.random.choice((j), 20)] = np.nan

In [121]:
np.set_printoptions(threshold = np.nan) 

In [122]:
iris_2d[:10]

array([[b'5.1', b'3.5', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.0', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.7', b'3.2', b'1.3', b'0.2', b'Iris-setosa'],
       [b'4.6', b'3.1', b'1.5', b'0.2', b'Iris-setosa'],
       [b'5.0', b'3.6', b'1.4', b'0.2', b'Iris-setosa'],
       [b'5.4', b'3.9', b'1.7', b'0.4', b'Iris-setosa'],
       [b'4.6', b'3.4', b'1.4', b'0.3', b'Iris-setosa'],
       [b'5.0', b'3.4', b'1.5', b'0.2', b'Iris-setosa'],
       [b'4.4', b'2.9', b'1.4', b'0.2', b'Iris-setosa'],
       [b'4.9', b'3.1', b'1.5', b'0.1', b'Iris-setosa']], dtype=object)

In [122]:
arr

array([[1.328285, 9.013704, 9.828288, 1.539478, 9.014914, 6.192113,
        7.682317, 6.671655, 6.23658 , 1.183952, 2.890239, 5.902164,
        7.922037, 3.256257, 3.573061]])

In [123]:
arr = np.random.uniform(1,10, size = (3,3))
arr

array([[4.964185, 4.642816, 4.980286],
       [1.27111 , 7.984048, 5.958625],
       [4.429661, 5.763392, 9.611892]])

In [124]:
i , j = np.where(arr)

In [125]:
i

array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64)

In [126]:
j

array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64)

In [129]:
np.random.seed(100)
arr[np.random.choice((i), 4), np.random.choice((j), 4)] = np.nan

In [130]:
arr

array([[4.964185,      nan, 4.980286],
       [1.27111 ,      nan, 5.958625],
       [     nan,      nan,      nan]])

In [131]:
# finding the missing value(nan) and position 

# Solution
print("Number of missing values: ", np.isnan(arr[:,:]).sum())
print("Position of missing values: ", np.where(np.isnan(arr)))



Number of missing values:  5
Position of missing values:  (array([0, 1, 2, 2, 2], dtype=int64), array([1, 1, 0, 1, 2], dtype=int64))


In [135]:
np.random.seed(100)
a = np.random.rand(4)
a

array([0.543405, 0.278369, 0.424518, 0.844776])

In [136]:
np.random.seed(100)
a = np.random.rand(4)

In [137]:
a

array([0.543405, 0.278369, 0.424518, 0.844776])

In [138]:
any_nan_in_row = np.array([~np.any(np.isnan(row)) for row in arr])
arr[any_nan_in_row]

array([], shape=(0, 3), dtype=float64)

In [139]:
a = np.arange(9).reshape(3,3)

In [140]:
any_nan_in_row = np.array([~np.any(np.isnan(row)) for row in a])
a[any_nan_in_row]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [141]:
# How to drop rows that contain a missing value from a numpy array

# first if matrix contain nan
# method 1
any_nan_in_row = np.array([~np.any(np.isnan(row)) for row in arr])
arr[any_nan_in_row]

array([], shape=(0, 3), dtype=float64)

In [142]:
#second if matrix not contain nan
#method 1
any_nan_in_row = np.array([~np.any(np.isnan(row)) for row in a])
a[any_nan_in_row]

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [149]:
np.random.seed(100)
b = np.random.uniform(5,10, size = (3,3))
b[np.random.choice((i), 2), np.random.choice((j), 2)] = np.nan

In [150]:
b

array([[7.717025, 6.391847, 7.122588],
       [     nan, 5.023594, 5.607846],
       [     nan, 9.129264, 5.683533]])

In [153]:
any_nan_in_row = np.array([~np.any(np.isnan(row)) for row in b])
b[any_nan_in_row]


array([[7.717025, 6.391847, 7.122588]])

In [154]:
# to find the correlation between two columns of a numpy array?

vector = np.random.uniform(1,10,size = (10,2))

In [155]:
vector 

array([[3.766809, 9.551659],
       [2.139888, 1.710891],
       [3.802178, 6.691452],
       [7.29423 , 6.777685],
       [9.280214, 3.689887],
       [6.11871 , 2.607619],
       [5.793163, 6.820223],
       [2.278588, 6.232501],
       [5.312709, 4.477772],
       [4.964185, 4.642816]])

In [158]:
#solution 1
np.corrcoef(vector[:,0],vector[:,1])

array([[ 1.      , -0.101788],
       [-0.101788,  1.      ]])

In [161]:
# Solution 2
from scipy.stats.stats import pearsonr  
corr, p_value = pearsonr(vector[:, 0], vector[:, 1])
print(corr)

-0.10178806783496926


In [162]:
p_value

0.779631248459767

In [164]:
# How to find if a given array has any null values

#for the arr
arr   # contain null value
np.isnan(arr).any() 

True

In [165]:
a #dose'nt have any null value

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [166]:
np.isnan(a).any()

False

In [167]:
b  #contain tow nan value in matrix b

array([[7.717025, 6.391847, 7.122588],
       [     nan, 5.023594, 5.607846],
       [     nan, 9.129264, 5.683533]])

In [168]:
np.isnan(b).any()

True

In [169]:
# to replace all missing values with 0 in a numpy array?
b[np.isnan(b)] = 0  # b contain two nan value

In [170]:
b

array([[7.717025, 6.391847, 7.122588],
       [0.      , 5.023594, 5.607846],
       [0.      , 9.129264, 5.683533]])

In [171]:
a[np.isnan(a)] = 0  # this function doest not work as their is no nan value
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [173]:
arr  # contain four nan value 
arr[np.isnan(arr)] = 0
arr

array([[4.964185, 0.      , 4.980286],
       [1.27111 , 0.      , 5.958625],
       [0.      , 0.      , 0.      ]])

In [186]:
# to find the count of unique values in a numpy array

vec = np.array((1,2,3,1,2,3,4,5,4,5,6,6,6,7,7,8)).tolist()
vec

[1, 2, 3, 1, 2, 3, 4, 5, 4, 5, 6, 6, 6, 7, 7, 8]

In [187]:
np.unique(vec, return_counts = True)

(array([1, 2, 3, 4, 5, 6, 7, 8]), array([2, 2, 2, 2, 2, 3, 2, 1], dtype=int64))

In [188]:
# it work on both the array and list   # first array give the unique value and 
# second array give number of occurence of unique value 
ve = np.array((1,2,3,1,2,3,4,5,4,5,6,6,6,7,7,8))
np.unique(ve, return_counts = True)

(array([1, 2, 3, 4, 5, 6, 7, 8]), array([2, 2, 2, 2, 2, 3, 2, 1], dtype=int64))

In [45]:
import numpy as np

In [46]:
#  to create a new column from existing columns of a numpy array

arr = np.random.uniform(1,10, size = (3,3))
arr

array([[8.93125267, 9.73259625, 6.93783574],
       [6.40350004, 4.79810841, 6.17338971],
       [8.43005017, 5.31574502, 4.31202578]])

In [47]:
# seperating the columns 
#column 1
col1 = arr[:,0]
col1

array([8.93125267, 6.40350004, 8.43005017])

In [48]:
#column 2
col2 = arr[:,1]
col2

array([9.73259625, 4.79810841, 5.31574502])

In [49]:
# column 3 
col3 = arr[:,2]
col3

array([6.93783574, 6.17338971, 4.31202578])

In [50]:
# volume = col1 * col2 * col3
volume = col1 * col2 * col3
volume 

array([603.06634942, 189.67546875, 193.23048715])

In [51]:
# # Introduce new dimension to match arr
volume = volume[:, np.newaxis]

In [52]:
volume

array([[603.06634942],
       [189.67546875],
       [193.23048715]])

In [53]:
# Add the new column

new_arr = np.hstack([arr, volume])
new_arr

array([[  8.93125267,   9.73259625,   6.93783574, 603.06634942],
       [  6.40350004,   4.79810841,   6.17338971, 189.67546875],
       [  8.43005017,   5.31574502,   4.31202578, 193.23048715]])

In [54]:
#  to do probabilistic sampling in numpy
# Import iris keeping the text column intact
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris = np.genfromtxt(url, delimiter=',', dtype='object')

In [59]:
species = iris[:, 4]

In [63]:
# Approach 1: Generate Probablistically
np.random.seed(100)
a = np.array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'])
species_out = np.random.choice(a, 150, p=[0.5, 0.25, 0.25])


In [67]:
# Approach 2: Probablistic Sampling (preferred)
np.random.seed(100)
probs = np.r_[np.linspace(0, 0.500, num=50), np.linspace(0.501, .750, num=50), np.linspace(.751, 1.0, num=50)]
index = np.searchsorted(probs, np.random.random(150))
species_out = species[index]
index
#print(np.unique(species_out, return_counts=True))

array([ 59,  28,  42, 119,   1,  12,  84, 115,  14,  65, 128,  21,  19,
        11,  22, 145, 112,  17, 113,  27,  43, 138, 114,  33,  18,  37,
         1,  25, 109,   2,  70,  71,  11,  38,   4, 128, 146,   6, 128,
        65,  98,  76,  66,   3,  21,  59, 104,  25,  29, 120, 145, 127,
        36,  70,  35,  34,  18,  24,   5,  51,  37,  69,  76,  14, 136,
       139,  70,  39,  36,  21,  28,  25,  18, 143, 141,  70,  96,  34,
        10,  46,  52,   9,  56, 148,  39,  33, 111, 101,  31,  77,  58,
        30,  11,  31,  45,  82,  25,  78,  20,  81, 106, 106,  72,  31,
        89, 122,  75, 146, 145,  17,   3,  16, 134, 140,  21,  36,  60,
        27,  46,  89,  50,  93,  55,   1,  39,  49,  40,  35,  50,  44,
         9,  27, 138,   3,   4,  28,  67, 148, 148, 148,  11,  83,  55,
        17, 138,  24, 149,  67,  18,  38], dtype=int64)

In [82]:
arr = np.random.random(10)
arr

array([0.29982006, 0.30838671, 0.10100427, 0.2950217 , 0.72890479,
       0.34187889, 0.28606816, 0.95634761, 0.99947915, 0.33735192])

In [84]:
ind = np.searchsorted(arr,np.random.random(10))
ind

array([7, 7, 0, 7, 8, 4, 4, 3, 7, 4], dtype=int64)

In [116]:
 out = arr[arr[:,0].argsort()] #ssorting the first column
out


array([[[6.72331408, 7.16880131],
        [8.42137103, 9.40740392],
        [1.07716524, 4.69801107],
        [5.66685399, 9.7977703 ],
        [4.33914702, 8.18034436],
        [4.37249597, 8.10534299],
        [2.29608466, 4.10978145],
        [6.37314406, 7.3095114 ],
        [7.69142681, 9.56224042],
        [3.76006662, 8.95701422]]])

In [115]:
out = out[out[:,1].argsort()] # sorting the second column
out

array([[[4.69801107, 1.07716524],
        [2.29608466, 4.10978145],
        [7.3095114 , 6.37314406],
        [7.16880131, 6.72331408],
        [4.37249597, 8.10534299],
        [4.33914702, 8.18034436],
        [3.76006662, 8.95701422],
        [8.42137103, 9.40740392],
        [7.69142681, 9.56224042],
        [5.66685399, 9.7977703 ]]])

In [107]:
# sort the data rowise

ar = np.random.uniform(0,10, size = (2,5))
ar

array([[9.89265639, 0.82825288, 7.11469926, 2.73154417, 9.94941426],
       [3.54727914, 0.88625414, 9.83250377, 4.79242982, 4.8216702 ]])

In [114]:
# sort  row
ar[ar.sort()]

array([[[0.82825288, 2.73154417, 7.11469926, 9.89265639, 9.94941426],
        [0.88625414, 3.54727914, 4.79242982, 4.8216702 , 9.83250377]]])

In [120]:
# to find the most frequent value in a numpy array

a = np.array([1,1,1,2,2,2,3,3,3,3,4,4,4,4,4,4,4,4,4,4,5,5,5,6,7,8])
a

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5,
       5, 6, 7, 8])

In [121]:
vals, count = np.unique(a, return_counts = True)

In [122]:
print(vals, count)

[1 2 3 4 5 6 7 8] [ 3  3  4 10  3  1  1  1]


In [123]:
print(vals[np.argmax(count)])

4


In [124]:
#  to find the position of the first occurrence of a value greater than a given value 
import numpy as np

In [132]:
arr = np.random.uniform(0,10, size = (10,1))
arr

array([[6.78942884],
       [1.7181999 ],
       [7.09573944],
       [4.89323385],
       [4.41921269],
       [6.46575798],
       [4.78433582],
       [7.80983565],
       [5.6378446 ],
       [8.49160372]])

In [137]:
np.argwhere(arr[:,0] > 7.0)

array([[2],
       [7],
       [9]], dtype=int64)

In [138]:
# to replace all values greater than a given value to a given cutoff 

np.random.seed(100)
ar = np.random.uniform(1,50,20)

In [149]:
ar
np.set_printoptions(precision = 2)

In [150]:
# solution 1
np.clip(ar, a_min = 10, a_max = 30)

array([27.63, 14.64, 21.8 , 30.  , 10.  , 10.  , 30.  , 30.  , 10.  ,
       29.18, 30.  , 11.25, 10.08, 10.  , 11.77, 30.  , 30.  , 10.  ,
       30.  , 14.43])

In [153]:
# solution 2
np.where(ar < 10, 10, np.where(ar > 30, 30, ar))

array([27.63, 14.64, 21.8 , 30.  , 10.  , 10.  , 30.  , 30.  , 10.  ,
       29.18, 30.  , 11.25, 10.08, 10.  , 11.77, 30.  , 30.  , 10.  ,
       30.  , 14.43])

In [162]:
# to get the positions of top n values from a numpy array
ar.sort()
ar[:5]

array([1.23, 6.31, 6.96, 7.7 , 9.43])

In [164]:
# solution 
np.argpartition(-ar, 5)[:5]

array([19, 18, 17, 16, 15], dtype=int64)